name: Python Calculator CI/CD

on:
  push:
    branches:
      - main
      - features/**
      - hotfix/**
      - release/**
  pull_request:
    branches:
      - main
      - features/**
      - hotfix/**
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests
        run: |
          python -m unittest discover

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t python-calculator .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag python-calculator:latest ${{ secrets.DOCKER_USERNAME }}/python-calculator:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/python-calculator:latest
